### PR TITLE
New feature display instance name

### PR DESCRIPTION
**Pull request by sd-tm**
If we have more than one Benchmark. Now can show us which Benchmark it is.

With some Unit Test too.

### CODE REVIEW

**Comment by sd-tm** [comment]
i like the tool!!

But i don't want add my Name on header.

Thank you for the merge!

**Comment by sd-tm** [comment]
You will add a new Version Tag?

**Comment by ucsdmath** [comment]
By this weekend I will bump the feature.  Thanks again.

**Comment by sd-tm** [comment]
😃

**Pull request merged**
